---
  - name: Metricbeat Playbook
    hosts: webservers
    become: true
    tasks: 

    - name: Download Metricbeat deb File
      get_url:
        url: "https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.8.1-amd64.deb"
        dest: /home/azadmin/metricbeat.deb

    - name: Install Metricbeat deb
      apt:
        deb: /home/azadmin/metricbeat.deb

    - name: Copy Configuration
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable and Configure the Docker Module
      command: metricbeat modules enable docker

    - name: Metricbeat Setup
      command: metricbeat setup

    - name: Start Metricbeat
      service: 
        name: metricbeat
        state: started
        enabled: yes
